-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PROJECTS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PROJECTS` ;

-- -----------------------------------------------------
-- Schema PROJECTS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PROJECTS` DEFAULT CHARACTER SET utf8 ;
USE `PROJECTS` ;

-- -----------------------------------------------------
-- Table `PROJECTS`.`CUSTOMERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROJECTS`.`CUSTOMERS` ;

CREATE TABLE IF NOT EXISTS `PROJECTS`.`CUSTOMERS` (
  `ID_HASH` VARCHAR(45) NOT NULL,
  `PUH` VARCHAR(45) NOT NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  `COMPANY` VARCHAR(45) NOT NULL,
  `CONTACT_TIME` DATETIME NOT NULL,
  `RESPOND_BY` DATETIME NOT NULL,
  PRIMARY KEY (`ID_HASH`),
  UNIQUE INDEX `idtable1_UNIQUE` (`ID_HASH` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PROJECTS`.`PROJECT_DATA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PROJECTS`.`PROJECT_DATA` ;

CREATE TABLE IF NOT EXISTS `PROJECTS`.`PROJECT_DATA` (
  `PROJECT_ID` INT NOT NULL AUTO_INCREMENT,
  `SHORT_DESC` TINYTEXT NOT NULL,
  `LONG_DESC` LONGTEXT NULL,
  `CUSTOMERS_ID_HASH` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PROJECT_ID`, `CUSTOMERS_ID_HASH`),
  INDEX `fk_PROJECT_DATA_CUSTOMERS_idx` (`CUSTOMERS_ID_HASH` ASC) VISIBLE,
  CONSTRAINT `fk_PROJECT_DATA_CUSTOMERS`
    FOREIGN KEY (`CUSTOMERS_ID_HASH`)
    REFERENCES `PROJECTS`.`CUSTOMERS` (`ID_HASH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
