# syntax=docker/dockerfile:1
FROM php:8.2-apache

# Install required mysqli extension for php
RUN docker-php-ext-install mysqli

# Install required packages for Composer
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install composer
COPY --from=composer/composer:2.2-bin /composer /usr/bin/composer