# syntax=docker/dockerfile:1
FROM php:8.2-apache
RUN docker-php-ext-install mysqli

# Install required packages and Composer
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

